#include "STD_types.h"

#include "DIO_interface.h"
#include "STEPPER_MOTOR_config.h"
#include "STEPPER_MOTOR_interface.h"
#include <util/delay.h>


void STEPPER_MOTOR_voidSetDegreeACW(f32 copy_u8Degree )
{

	u16 Local_u8NoOfSteps, Local_u8NoofIterations;

	Local_u8NoOfSteps=(copy_u8Degree/(0.175));

	Local_u8NoofIterations= (Local_u8NoOfSteps/4);

	for(int i=0;i<=Local_u8NoofIterations;i++)
	{

		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,BLUE_PIN0,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,PINK_PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,YELLOW_PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,ORANGE_PIN3,DIO_u8PIN_LOW);
		_delay_ms(2);

		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,BLUE_PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,PINK_PIN1,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,YELLOW_PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,ORANGE_PIN3,DIO_u8PIN_LOW);
		_delay_ms(2);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,BLUE_PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,PINK_PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,YELLOW_PIN2,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,ORANGE_PIN3,DIO_u8PIN_LOW);
		_delay_ms(2);

		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,BLUE_PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,PINK_PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,YELLOW_PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,ORANGE_PIN3,DIO_u8PIN_HIGH);
		_delay_ms(2);
	}
}

void STEPPER_MOTOR_voidSetDegreeCW(f32 copy_u8Degree )
{

	u16 Local_u8NoOfSteps, Local_u8NoofIterations;

	Local_u8NoOfSteps=(copy_u8Degree/(0.175));

	Local_u8NoofIterations= (Local_u8NoOfSteps/4);

	for(int i=0;i<=Local_u8NoofIterations;i++)
	{

		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,BLUE_PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,PINK_PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,YELLOW_PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,ORANGE_PIN3,DIO_u8PIN_HIGH);
		_delay_ms(2);

		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,BLUE_PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,PINK_PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,YELLOW_PIN2,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,ORANGE_PIN3,DIO_u8PIN_LOW);
		_delay_ms(2);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,BLUE_PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,PINK_PIN1,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,YELLOW_PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,ORANGE_PIN3,DIO_u8PIN_LOW);
		_delay_ms(2);

		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,BLUE_PIN0,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,PINK_PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,YELLOW_PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_MOTOR_PORT,ORANGE_PIN3,DIO_u8PIN_LOW);
		_delay_ms(2);
	}
}
