#include "STD_TYPES.h"
#include "DIO_interface.h"
#include "STEPPER_interface.h"
#include "STEPPER_config.h"
#include <util/delay.h>




void Stepper_u8CW(f32 angle)
{

	u16 count =0 ;
	u16 steps ;

	//DIO_u8SetPortValue(STEPPER_U8PORT,DIO_u8PORT_HIGH);

	steps = ((angle /0.175)/4);

	for (count=0 ; count<=steps ; count ++)
	{

		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN0,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN3,DIO_u8PIN_LOW);

		_delay_ms(2);

		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN1,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN3,DIO_u8PIN_LOW);

		_delay_ms(2);

		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN2,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN3,DIO_u8PIN_LOW);

		_delay_ms(2);

		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN3,DIO_u8PIN_HIGH);

		_delay_ms(2);



	}

}


void Stepper_u8ACW(f32 angle)
{
	u8 count =0 ;
	u16 steps ;

	//DIO_u8SetPortValue()(STEPPER_U8PORT ,DIO_u8PORT_HIGH);

	steps = ((angle /0.175)/4);


	for (count=0 ; count<=steps ; count ++)
	{


		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN3,DIO_u8PIN_HIGH);

		_delay_ms(2);

		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN2,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN3,DIO_u8PIN_LOW);

		_delay_ms(2);

		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN0,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN1,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN3,DIO_u8PIN_LOW);

		_delay_ms(2);

		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN0,DIO_u8PIN_HIGH);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN1,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN2,DIO_u8PIN_LOW);
		DIO_u8SetPinValue(STEPPER_U8PORT,STEPPER_U8PIN3,DIO_u8PIN_LOW);

		_delay_ms(2);

	}
}

